### PR TITLE
A fix for Cappuccino issue 759.

### PR DESCRIPTION
**Pull request by danielphelps**
Hi All,
   I have a fix that enables tusk to use the http_proxy environment variable.
Relevant: http://groups.google.com/group/narwhaljs/browse_thread/thread/33cd58b80db5b7a8/a7c95963b272f117

   Before this fix, the JVM would always assume that no proxy was needed for internet connectivity (unless configured otherwise).  Now, the http proxy hostname and port are supplied as arguments for java in the narwhal-rhino script.  This information is now utilized in the http-client-engine.

   The change was very small.

   Also, I noticed that a CLA is required for cappuccino -- is it also required for narwhal?  If so, let me know and I will take care of that.  

Thank you,
Daniel Phelps

### CODE REVIEW

**Comment by paulbaumgart** [comment]
Here's the answer to my question: http://stackoverflow.com/questions/1626549/authenticated-http-proxy-with-java

Feel like taking this one on? Otherwise I'll get around to it later today.

**Comment by danielphelps** [comment]
I would like to do it, but mid terms are creeping up.  It will probably be Saturday or Sunday before I can do it.

**Comment by paulbaumgart** [comment]
Ok, that's fine. Let me know if you have any questions.

**Comment by danielphelps** [comment]
I'm not sure if this is OK.  In engines/rhino/bin/narwhal-rhino, I'm using the Ruby URI module to help parse the http_proxy variable.  Perhaps there is a better way to do this.  

Please take a look and see what you think.

**Comment by paulbaumgart** [comment]
Thanks, I made a few tweaks, using the URI module to parse http_proxy instead:

https://github.com/280north/narwhal/commit/86915a6e590e3386b9e6775192a2d3bdb9bcca87

Can you review the changes and make sure it still works as advertised?

**Comment by danielphelps** [comment]
Hi Paul, 
   Sorry it took me so long.  Your change is much better and it works as advertised.

**Pull request closed without merging**
